init db schemas
developerKhusanjon/doc-management-system pull request #1
Opened 2022-10-19 10:44 UTC by developerKhusanjon

2022-10-19 10:51 UTC, VladimirBaklan requested changes

2022-10-19 10:51 UTC, VladimirBaklan commented on .bsp/sbt.json
> +{"name":"sbt","version":"1.7.2","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["/Users/khusanjon/Library/Java/JavaVirtualMachines/openjdk-19/Contents/Home/bin/java","-Xms100m","-Xmx100m","-cla
Please fix .gitignore

2022-10-19 10:51 UTC, VladimirBaklan commented on docker/sql/docmg.sql
> +ALTER TABLE admins
You should define constraints when you create a table without using `alter table`

2022-10-19 10:51 UTC, VladimirBaklan commented on docker/sql/docmg.sql
> +-- Employees
Comments are too obvious here, no need to add it

2022-10-19 10:51 UTC, VladimirBaklan commented on docker/sql/docmg.sql
> +  content character varying NOT NULL
What is `content`?

2022-10-19 10:51 UTC, VladimirBaklan commented on docker/sql/docmg.sql
> +  content character varying NOT NULL
And how would you store submissions?

2022-10-19 10:51 UTC, VladimirBaklan commented on docker/sql/docmg.sql
> +  id uuid NOT NULL,
It makes more sense to use auto-generated primary keys, like SERIAL/BIGSERIAL

2022-10-19 10:51 UTC, VladimirBaklan commented on docker/sql/docmg.sql
> +  name character varying NOT NULL,
`character varying` => `varchar`

2022-10-19 10:51 UTC, VladimirBaklan commented on docker/sql/docmg.sql
> +ALTER TABLE admins
Why do you store users and admins separately?

2022-10-19 10:51 UTC, VladimirBaklan commented on project/plugin.sbt
> +addSbtPlugin("io.github.davidmweber" % "flyway-sbt" % "7.4.0")
I don't see configurations for plugin

2022-10-19 14:59 UTC, VladimirBaklan commented on docker/sql/docmg.sql
> +  description varchar NOT NULL
What is the description?

2022-10-19 15:19 UTC, developerKhusanjon commented on docker/sql/docmg.sql
> +  description varchar NOT NULL
I just added for extra info about webform... it describes what kind of form you are submitting

2022-10-19 15:30 UTC, VladimirBaklan commented on docker/sql/docmg.sql
> +  description varchar NOT NULL
How would you store elements from webform? Webform has dynamic configuration as described in the task

2022-10-19 15:40 UTC, developerKhusanjon commented on docker/sql/docmg.sql
> +  description varchar NOT NULL
I'm looking for this but for now, I haven't an exact solution... maybe I can add another table as form_field or like that with ManyToOne relationship with webform

2022-10-19 18:09 UTC, developerKhusanjon commented on docker/sql/docmg.sql
> +  description varchar NOT NULL
Could do suggest something, please?

2022-10-19 18:09 UTC, developerKhusanjon commented on docker/sql/docmg.sql
> +  description varchar NOT NULL
Could do suggest something, please?

2022-10-22 07:54 UTC, VladimirBaklan commented on src/main/scala/dev/khusanjon/docmngsys/company/CompanyRegistry.scala
> +final case class Company(name: String, address: String)
Why final?

2022-10-28 12:41 UTC, closed without merging